name: Release Python

on:
  push:
    tags:
      - 'py-v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Run Python tests
      run: |
        cd src/python
        ls
        pip install -e ".[dev]"
        python -m pytest
    - name: Install and build dependencies
      run: |
        cd src/python
        ls
        python -m pip install --upgrade pip
        pip install build twine
        python -m build
        ls
        twine upload --repository testpypi dist/* --verbose
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true